// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOM7O3k28b7ZDkuoB-IDi1Ju0sHzR1cWA',
    appId: '1:193045073614:web:c13e2b2e5565591dab4a9f',
    messagingSenderId: '193045073614',
    projectId: 'fluttertodoexample',
    authDomain: 'fluttertodoexample.firebaseapp.com',
    storageBucket: 'fluttertodoexample.appspot.com',
    measurementId: 'G-4HBKJ927EW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXJ5qS_WOdRMRRfBpuhhowL41fQCJWx34',
    appId: '1:193045073614:android:6b4db1788d610c8dab4a9f',
    messagingSenderId: '193045073614',
    projectId: 'fluttertodoexample',
    storageBucket: 'fluttertodoexample.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA43MpDSr53pBkvVqk5X6VelcyZxBSPGmw',
    appId: '1:193045073614:ios:4795a3df8a916bb4ab4a9f',
    messagingSenderId: '193045073614',
    projectId: 'fluttertodoexample',
    storageBucket: 'fluttertodoexample.appspot.com',
    iosClientId: '193045073614-llqu7qrofesv1f0fsfsuad1tlco36bt3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTodoExample',
  );
}
